import {
  DataSourceItem,
  ProcessingJobItem,
  EvidenceItem,
  ReportItem,
  ReportSectionNode,
  EditorBlock,
  AssetRecord,
  ValidationIssueItem,
  AuditLogItem,
  SystemHealthComponent,
  SystemSecurityPosture,
} from '../types';

export const INITIAL_SECURITY_POSTURE: SystemSecurityPosture = {
  localAiStatus: 'Connected (llama.cpp 127.0.0.1:8484)',
  externalAiStatus: 'Strictly Disabled (Airgapped Firewall Active)',
  networkAccess: 'Restricted (Loopback Only)',
  auditLogging: 'Enabled (Tamper-Evident SHA-256 Ledger)',
  credentialStorage: 'Local OS Keyring (Zero Cloud Tokens)',
  gpuStatus: 'NVIDIA RTX 4090 (24GB VRAM Allocated: 14.8GB)',
  encryptionStatus: 'AES-256 at-rest (Local Workspace Partition)',
};

export const INITIAL_HEALTH_COMPONENTS: SystemHealthComponent[] = [
  {
    id: 'ocr',
    name: 'OCR Engine',
    engine: 'PaddleOCR v2.8 + Tesseract 5.4 (CUDA 12.4)',
    status: 'healthy',
    detail: 'Dual-pass multilingual OCR running on local GPU tensor cores',
    metrics: '99.4% char accuracy • 38 ms/page',
    latency: '38ms',
    device: 'CUDA:0 (RTX 4090)',
  },
  {
    id: 'parser',
    name: 'Document Parser',
    engine: 'PyMuPDF + Unstructured-Local (C++ bindings)',
    status: 'healthy',
    detail: 'Extracts layout hierarchy, tables (Lattice/Stream), and image vectors',
    metrics: '14,820 pages processed without fault',
    latency: '14ms/doc',
    device: 'Host CPU (16 threads)',
  },
  {
    id: 'search',
    name: 'Search Index',
    engine: 'Qdrant Embedded + SQLite BM25 Hybrid',
    status: 'healthy',
    detail: 'Dense 1024-dim BGE-M3 vectors + sparse lexical BM25 index on NVMe',
    metrics: '48,290 passage chunks • 1.2 GB index size',
    latency: '4.2ms query',
    device: 'Local NVMe SSD',
  },
  {
    id: 'model',
    name: 'Local AI Model',
    engine: 'Llama-3.3-70B-Instruct-Q4_K_M (llama.cpp server)',
    status: 'healthy',
    detail: 'Airgapped local LLM with 32,768 token context window & zero internet egress',
    metrics: '28.4 tokens/sec • 14.8 GB VRAM locked',
    latency: '22ms TTFT',
    device: 'NVIDIA GPU (CUDA)',
  },
  {
    id: 'renderer',
    name: 'PDF Renderer',
    engine: 'Typst CLI 0.11 + Weasyprint Enterprise',
    status: 'healthy',
    detail: 'High-precision deterministic corporate layout engine with vector CMYK support',
    metrics: 'Pre-flight check active • PDF/A-2b compliant',
    latency: '1.4s / 60 pages',
    device: 'Local Subprocess',
  },
];

export const INITIAL_REPORTS: ReportItem[] = [
  {
    id: 'rep-001',
    name: 'MineIntel Consolidated Operational & Financial Review (Q3 FY26)',
    organization: 'MineIntel / Corporate Planning & Operations',
    reportingPeriod: 'October 1, 2025 – December 31, 2025',
    description: 'Comprehensive quarterly corporate evaluation covering 8 regional operating subsidiaries, raw coal offtake, CapEx realization, and environmental compliance.',
    createdAt: '2026-02-14 09:30',
    lastModified: '2026-02-28 16:45',
    status: 'In Progress',
    sectionsCount: 8,
    wordCount: 14850,
    sourcesLinkedCount: 34,
    validationScore: 92,
    referenceReportUsed: 'CIL_Annual_Report_FY25_Audited_Reference.pdf',
    selectedModel: 'Llama-3.3-70B-Instruct-Q4_K_M (Local)',
  },
  {
    id: 'rep-002',
    name: 'Mahanadi Coalfields Heavy Machinery CapEx & Lifecycle Audit',
    organization: 'MCL Subsidiary / Sambalpur Directorate',
    reportingPeriod: 'FY 2025-2026 YTD',
    description: 'Special technical audit on dragline excavator utilization, maintenance downtime, and replacement procurement ledgers.',
    createdAt: '2026-02-10 11:20',
    lastModified: '2026-02-24 14:15',
    status: 'Validated',
    sectionsCount: 6,
    wordCount: 9420,
    sourcesLinkedCount: 19,
    validationScore: 98,
    referenceReportUsed: 'Technical_CapEx_Standard_Reference_2024.pdf',
    selectedModel: 'Gemma-2-27B-IT-Q5_K_M (Local)',
  },
  {
    id: 'rep-003',
    name: 'Environmental Clearance & Mine Rehabilitation Statutory Filing',
    organization: 'Central Mine Planning & Design Institute (CMPDI)',
    reportingPeriod: 'Annual Statutory Cycle 2025',
    description: 'Submitted to Ministry of Coal & Forest Advisory Committee. Ground water levels, afforestation metrics, and fly-ash disposal telemetry.',
    createdAt: '2026-01-15 08:00',
    lastModified: '2026-02-02 17:30',
    status: 'Exported',
    sectionsCount: 11,
    wordCount: 22400,
    sourcesLinkedCount: 52,
    validationScore: 100,
    referenceReportUsed: 'MoEFCC_Statutory_Template_Archive.pdf',
    selectedModel: 'Llama-3.3-70B-Instruct-Q4_K_M (Local)',
  },
];

export const INITIAL_DATA_SOURCES: DataSourceItem[] = [
  {
    id: 'src-001',
    filename: 'CIL_FY26_Q3_Consolidated_Financial_Ledger.xlsx',
    type: 'XLSX',
    sizeBytes: 14280192,
    dateModified: '2026-02-18 14:22',
    sourcePath: '/data/local_repos/finance/q3/CIL_FY26_Q3_Consolidated_Financial_Ledger.xlsx',
    processingStatus: 'indexed',
    pages: 14,
    ocrStatus: 'Not Required',
    indexedStatus: 'Indexed',
    extractedTablesCount: 28,
    extractedImagesCount: 0,
    summary: 'Contains quarterly revenue breakdowns by subsidiary, realization per ton, royalty payments, and tax accruals.',
    checksum: 'sha256:4a8b9f10d291e0a98b1c4e9f',
  },
  {
    id: 'src-002',
    filename: 'Mahanadi_Coalfields_Safety_Inspection_Scanned_Dec25.pdf',
    type: 'Scanned PDF',
    sizeBytes: 48920110,
    dateModified: '2026-01-20 09:14',
    sourcePath: '/data/local_repos/safety/scans/Mahanadi_Coalfields_Safety_Inspection_Scanned_Dec25.pdf',
    processingStatus: 'indexed',
    pages: 42,
    ocrStatus: 'Completed',
    indexedStatus: 'Indexed',
    extractedTablesCount: 12,
    extractedImagesCount: 16,
    summary: 'Scanned field engineering inspections, gas detector logs, and pit slope stability measurements.',
    checksum: 'sha256:7f01bc49a90918d2ea56c321',
  },
  {
    id: 'src-003',
    filename: 'Eastern_Coalfields_CapEx_and_Fleet_Downtime.csv',
    type: 'CSV',
    sizeBytes: 3840291,
    dateModified: '2026-02-12 18:05',
    sourcePath: '/data/local_repos/operations/Eastern_Coalfields_CapEx_and_Fleet_Downtime.csv',
    processingStatus: 'indexed',
    pages: 1,
    ocrStatus: 'Not Required',
    indexedStatus: 'Indexed',
    extractedTablesCount: 1,
    extractedImagesCount: 0,
    summary: 'High-frequency telemetry records on 142 dumpers, shovel excavators, and dragline maintenance intervals.',
    checksum: 'sha256:8899ac32e10419dfa4358891',
  },
  {
    id: 'src-004',
    filename: 'Board_Resolution_Renewable_CapEx_Solar_FY26.docx',
    type: 'DOCX',
    sizeBytes: 1940200,
    dateModified: '2026-02-05 11:45',
    sourcePath: '/data/local_repos/board_secretariat/Board_Resolution_Renewable_CapEx_Solar_FY26.docx',
    processingStatus: 'indexed',
    pages: 18,
    ocrStatus: 'Not Required',
    indexedStatus: 'Indexed',
    extractedTablesCount: 4,
    extractedImagesCount: 3,
    summary: 'Approved board resolution authorizing ₹1,250 Cr investment into 400MW ground-mounted solar farms.',
    checksum: 'sha256:19028abcef90123985718a24',
  },
  {
    id: 'src-005',
    filename: 'Western_Coalfields_Production_Telemetry_Summary.pdf',
    type: 'PDF',
    sizeBytes: 8940120,
    dateModified: '2026-02-14 16:10',
    sourcePath: '/data/local_repos/production/Western_Coalfields_Production_Telemetry_Summary.pdf',
    processingStatus: 'indexed',
    pages: 26,
    ocrStatus: 'Not Required',
    indexedStatus: 'Indexed',
    extractedTablesCount: 14,
    extractedImagesCount: 8,
    summary: 'Digital vector PDF detailing raw coal extraction vs targeted dispatch, railway rake availability, and silo stockpile levels.',
    checksum: 'sha256:91204857bcae9182374619a0',
  },
  {
    id: 'src-006',
    filename: 'Aerial_Drone_Surveys_Mine_Pit_A_OpenCast.png',
    type: 'Images',
    sizeBytes: 15820490,
    dateModified: '2026-02-15 10:02',
    sourcePath: '/data/local_repos/geospatial/Aerial_Drone_Surveys_Mine_Pit_A_OpenCast.png',
    processingStatus: 'indexed',
    pages: 1,
    ocrStatus: 'Completed',
    indexedStatus: 'Indexed',
    extractedTablesCount: 0,
    extractedImagesCount: 1,
    summary: 'High-resolution orthomosaic drone elevation map of Gevra opencast expansion with GIS perimeter coordinates.',
    checksum: 'sha256:6639210abced475891823746',
  },
  {
    id: 'src-007',
    filename: 'Statutory_Auditor_Preliminary_Observations_FY26.txt',
    type: 'TXT',
    sizeBytes: 420800,
    dateModified: '2026-02-26 19:40',
    sourcePath: '/data/local_repos/audit/Statutory_Auditor_Preliminary_Observations_FY26.txt',
    processingStatus: 'indexed',
    pages: 6,
    ocrStatus: 'Not Required',
    indexedStatus: 'Indexed',
    extractedTablesCount: 0,
    extractedImagesCount: 0,
    summary: 'Unformatted notes from Lead External Comptroller on environmental provision accounting and coal inventory valuation.',
    checksum: 'sha256:334455aabbccddeeff001122',
  },
];

export const INITIAL_PROCESSING_JOBS: ProcessingJobItem[] = [
  {
    id: 'job-101',
    jobName: 'Batch Ingestion: Q3 Financial & Operational Repositories',
    type: 'Full Ingestion',
    progress: 100,
    currentStage: 'Completed',
    startedAt: '2026-02-28 14:00',
    elapsedTime: '4m 12s',
    status: 'completed',
    errorsCount: 0,
    warningsCount: 2,
    filesProcessed: 7,
    totalFiles: 7,
    logs: [
      '[14:00:02] Local daemon initiated ingestion pipeline for 7 files in /data/local_repos',
      '[14:00:15] PyMuPDF extracted 26 pages from Western_Coalfields_Production_Telemetry_Summary.pdf',
      '[14:00:48] PaddleOCR GPU batch processed 42 scanned pages from Mahanadi_Coalfields_Safety_Inspection_Scanned_Dec25.pdf',
      '[14:01:30] Lattice table extractor identified 28 tabular matrices from CIL_FY26_Q3_Consolidated_Financial_Ledger.xlsx',
      '[14:02:10] Local BGE-M3 model generated 48,290 dense vector embeddings',
      '[14:03:50] Qdrant local vector store updated; hybrid BM25 inverted index flushed to NVMe disk',
      '[14:04:14] Pipeline completed successfully with 0 errors, 2 low-contrast image warnings',
    ],
  },
  {
    id: 'job-102',
    jobName: 'OCR Pass: High-Resolution Aerial Survey & Geological Core Logs',
    type: 'OCR Batch',
    progress: 74,
    currentStage: 'Table extraction',
    startedAt: '2026-02-28 16:20',
    elapsedTime: '1m 45s',
    status: 'running',
    errorsCount: 0,
    warningsCount: 0,
    filesProcessed: 18,
    totalFiles: 24,
    logs: [
      '[16:20:00] CUDA GPU context initialized on Device 0 (RTX 4090)',
      '[16:20:12] Batch scanning folder: /data/local_repos/geological_logs',
      '[16:20:45] Pages 1-18 processed at average 32ms per page',
      '[16:21:10] Extracting geological strata borehole data using Lattice table parser...',
      '[16:21:35] Worker thread #3 analyzing tabular bounding box coordinate grids...',
    ],
  },
  {
    id: 'job-103',
    jobName: 'Vector Embedding Sync: Historical Reference Archive (FY2020-FY2025)',
    type: 'Vector Re-Index',
    progress: 100,
    currentStage: 'Completed',
    startedAt: '2026-02-27 10:15',
    elapsedTime: '12m 04s',
    status: 'completed',
    errorsCount: 0,
    warningsCount: 1,
    filesProcessed: 54,
    totalFiles: 54,
    logs: [
      '[10:15:00] Initializing multi-year reference baseline index',
      '[10:22:18] Processed 1,480 historical report sections',
      '[10:27:04] Qdrant collection historical_reference_v2 built with HNSW M=16 ef=100',
    ],
  },
];

export const INITIAL_EVIDENCE_ITEMS: EvidenceItem[] = [
  {
    id: 'ev-001',
    documentId: 'src-001',
    documentName: 'CIL_FY26_Q3_Consolidated_Financial_Ledger.xlsx',
    documentType: 'XLSX',
    spreadsheetName: 'CIL_FY26_Q3_Consolidated_Financial_Ledger.xlsx',
    sheetName: 'March_Consolidated_Summary',
    cellRange: 'G27:G31',
    relevantText: 'Gross Operational Turnover Q3 FY26: ₹4,912.80 Cr (Reflects finalized pithead realized price of ₹1,642/ton across 29.91 MT of prime coking & non-coking coal dispatched). Prior provisional estimate was ₹4,820.50 Cr before reconciliation.',
    metadata: {
      year: 2025,
      month: 'December',
      organizationUnit: 'Directorate of Finance & Commercial Accounts',
      date: '2026-01-14',
      authorOrSource: 'Chief General Manager (Finance)',
    },
    confidence: 99.4,
    sourceLocation: 'Sheet: March_Consolidated_Summary | Col G, Rows 27-31',
    extractionMethod: 'Lattice Table Extractor',
    rawTableData: [
      ['Account Code', 'Subsidiary Branch', 'Dispatched Volume (MT)', 'Avg Realization/T', 'Gross Revenue (₹ Cr)'],
      ['4100-REV', 'BCCL Dhanbad', '8.45 MT', '₹2,140.00', '₹1,808.30 Cr'],
      ['4102-REV', 'CCL Ranchi', '6.12 MT', '₹1,580.00', '₹966.96 Cr'],
      ['4104-REV', 'MCL Sambalpur', '15.34 MT', '₹1,393.40', '₹2,137.54 Cr'],
      ['TOTAL', 'Consolidated Q3 Realization', '29.91 MT', '₹1,642.50', '₹4,912.80 Cr'],
    ],
  },
  {
    id: 'ev-002',
    documentId: 'src-005',
    documentName: 'Western_Coalfields_Production_Telemetry_Summary.pdf',
    documentType: 'PDF',
    page: 14,
    sectionName: 'Section 3.2 - Heavy Earth Moving Machinery (HEMM) Availability',
    relevantText: 'Average HEMM equipment availability in WCL opencast mines reached 84.6% in December 2025, surpassing the DGMS benchmark of 80.0%. Hydraulic shovels recorded 5,820 aggregate operating hours with a mean time between failures (MTBF) of 412 hours.',
    metadata: {
      year: 2025,
      month: 'December',
      organizationUnit: 'WCL Directorate of Engineering & Excavation',
      date: '2026-01-18',
      authorOrSource: 'Director (Technical / Operations)',
    },
    confidence: 98.8,
    sourceLocation: 'Page 14, Paragraph 3 | Bounding Box [45, 310, 520, 140]',
    extractionMethod: 'Native Parser',
    bbox: { x: 45, y: 310, width: 520, height: 140 },
  },
  {
    id: 'ev-003',
    documentId: 'src-002',
    documentName: 'Mahanadi_Coalfields_Safety_Inspection_Scanned_Dec25.pdf',
    documentType: 'Scanned PDF',
    page: 28,
    sectionName: 'Statutory Safety Audit & Zero-Harm Protocol Compliance',
    relevantText: 'Zero reportable fatalities registered across 14 opencast pits during the 90-day review period. Continuous atmospheric methane sensors and infrared pit-wall slope radars operated with 99.8% telemetric uptime.',
    metadata: {
      year: 2025,
      month: 'December',
      organizationUnit: 'Directorate General of Mines Safety (DGMS Liaison)',
      date: '2026-01-05',
      authorOrSource: 'Dy. Director General of Mines Safety (Eastern Zone)',
    },
    confidence: 96.2,
    sourceLocation: 'Page 28, Column B | OCR Box [60, 420, 480, 110]',
    extractionMethod: 'PaddleOCR GPU',
    bbox: { x: 60, y: 420, width: 480, height: 110 },
  },
  {
    id: 'ev-004',
    documentId: 'src-004',
    documentName: 'Board_Resolution_Renewable_CapEx_Solar_FY26.docx',
    documentType: 'DOCX',
    page: 4,
    sectionName: 'Item 4.3 - Net-Zero Transition & Ground Mounted Solar Arrays',
    relevantText: 'The Board resolved to sanction capital expenditure of ₹1,250 Crores for the Phase-II commissioning of 400 MW solar PV capacity across de-coaled mine voids in Sambalpur and Bilaspur, targeted for commercial operation by Q2 FY27.',
    metadata: {
      year: 2026,
      month: 'February',
      organizationUnit: 'Corporate Secretariat, Coal Bhawan Kolkata',
      date: '2026-02-05',
      authorOrSource: 'Company Secretary & Compliance Officer',
    },
    confidence: 99.1,
    sourceLocation: 'Page 4, Resolution No. CIL:BM:392:2026:Item4',
    extractionMethod: 'Native Parser',
  },
  {
    id: 'ev-005',
    documentId: 'src-003',
    documentName: 'Eastern_Coalfields_CapEx_and_Fleet_Downtime.csv',
    documentType: 'CSV',
    spreadsheetName: 'Eastern_Coalfields_CapEx_and_Fleet_Downtime.csv',
    sheetName: 'Sheet1',
    cellRange: 'A12:E19',
    relevantText: 'Equipment ID DRAG-04 (Rajmahal OCP): Total refurbishment CapEx incurred in Q3 was ₹48.50 Cr against allocated budget of ₹52.00 Cr. Returned to overburden stripping service on Nov 14, 2025.',
    metadata: {
      year: 2025,
      month: 'November',
      organizationUnit: 'ECL Rajmahal Area Excavation Division',
      date: '2025-11-20',
      authorOrSource: 'Superintending Excavation Engineer',
    },
    confidence: 97.9,
    sourceLocation: 'Row 12-19, Col A-E',
    extractionMethod: 'Lattice Table Extractor',
  },
];

export const INITIAL_REPORT_SECTIONS: ReportSectionNode[] = [
  {
    id: 'sec-1',
    title: '1. Executive Overview & Institutional Mandate',
    level: 1,
    aiRationale: 'Discovered high-level statutory KPIs across Board Resolution & Consolidated Summary. Formulates leadership synthesis.',
    linkedEvidenceCount: 8,
    status: 'validated',
    isLocked: true,
    wordCount: 1850,
    children: [
      {
        id: 'sec-1-1',
        title: '1.1 Consolidated Macroeconomic Environment & Fuel Security',
        level: 2,
        linkedEvidenceCount: 3,
        status: 'validated',
        wordCount: 820,
      },
      {
        id: 'sec-1-2',
        title: '1.2 High-Level Production & Offtake Summary',
        level: 2,
        linkedEvidenceCount: 5,
        status: 'validated',
        wordCount: 1030,
      },
    ],
  },
  {
    id: 'sec-2',
    title: '2. Operational Performance & Subsidiary Production',
    level: 1,
    aiRationale: 'Synthesized from 26-page Western Coalfields telemetry and Eastern Coalfields production CSVs.',
    linkedEvidenceCount: 14,
    status: 'drafted',
    wordCount: 3420,
    children: [
      {
        id: 'sec-2-1',
        title: '2.1 Raw Coal Extraction vs Annual Target Allocations',
        level: 2,
        linkedEvidenceCount: 6,
        status: 'drafted',
        wordCount: 1420,
      },
      {
        id: 'sec-2-2',
        title: '2.2 Heavy Earth Moving Machinery (HEMM) Availability & Fleet Telemetry',
        level: 2,
        linkedEvidenceCount: 5,
        status: 'validated',
        wordCount: 1100,
      },
      {
        id: 'sec-2-3',
        title: '2.3 Coal Washery Beneficiation & Grade Consistency',
        level: 2,
        linkedEvidenceCount: 3,
        status: 'planned',
        wordCount: 900,
      },
    ],
  },
  {
    id: 'sec-3',
    title: '3. Logistics, Evacuation & Railway Rake Allotment',
    level: 1,
    aiRationale: 'Identified bottleneck data between pithead silos and Indian Railways siding dispatch ledgers.',
    linkedEvidenceCount: 7,
    status: 'drafted',
    wordCount: 2150,
  },
  {
    id: 'sec-4',
    title: '4. Financial Performance & Commercial Realization',
    level: 1,
    aiRationale: 'Mapped directly to CIL_FY26_Q3_Consolidated_Financial_Ledger.xlsx (March Summary Sheet). High sensitivity numerical section.',
    linkedEvidenceCount: 18,
    status: 'review_required',
    wordCount: 4200,
    children: [
      {
        id: 'sec-4-1',
        title: '4.1 Turnover, Fuel Supply Agreement (FSA) Realizations & E-Auction Premiums',
        level: 2,
        linkedEvidenceCount: 10,
        status: 'review_required',
        wordCount: 2100,
      },
      {
        id: 'sec-4-2',
        title: '4.2 Capital Expenditure & Infrastructure Modernization Ledger',
        level: 2,
        linkedEvidenceCount: 8,
        status: 'drafted',
        wordCount: 2100,
      },
    ],
  },
  {
    id: 'sec-5',
    title: '5. Mine Safety, Risk Mitigation & Zero-Harm Protocol',
    level: 1,
    aiRationale: 'Corroborated by DGMS statutory inspection reports and scanned sensor logs.',
    linkedEvidenceCount: 9,
    status: 'validated',
    wordCount: 1980,
  },
  {
    id: 'sec-6',
    title: '6. Environmental Clearance, Land Reclamation & Net-Zero CapEx',
    level: 1,
    aiRationale: 'Generated from Board Resolution 4.3 (400MW Solar) and GIS orthomosaic drone surveys.',
    linkedEvidenceCount: 11,
    status: 'drafted',
    wordCount: 2400,
  },
  {
    id: 'sec-7',
    title: '7. Statutory Governance, Internal Audit & Regulatory Disclosures',
    level: 1,
    aiRationale: 'Includes External Comptroller observations and mandatory Ministry of Coal compliance disclosures.',
    linkedEvidenceCount: 6,
    status: 'planned',
    wordCount: 1600,
  },
];

export const INITIAL_EDITOR_BLOCKS: EditorBlock[] = [
  {
    id: 'blk-001',
    sectionId: 'sec-4-1',
    type: 'heading',
    level: 2,
    content: '4.1 Turnover, Fuel Supply Agreement (FSA) Realizations & E-Auction Premiums',
  },
  {
    id: 'blk-002',
    sectionId: 'sec-4-1',
    type: 'paragraph',
    content: 'During the third quarter of Fiscal Year 2025–26, MineIntel operational records show sustained robust cash flow driven by stabilized pithead realization across both regulated thermal power supply agreements and competitive spot e-auctions. Total raw coal dispatches across all eight operating subsidiaries reached 29.91 Million Tonnes (MT), representing a 4.8% expansion over the corresponding prior year period.',
    citationId: 'ev-001',
    evidenceRef: {
      documentName: 'CIL_FY26_Q3_Consolidated_Financial_Ledger.xlsx',
      location: 'Sheet: March_Consolidated_Summary | Col G, Rows 27-31',
      verified: true,
    },
  },
  {
    id: 'blk-003',
    sectionId: 'sec-4-1',
    type: 'callout',
    calloutType: 'audit',
    content: 'STATUTORY AUDIT RECONCILIATION NOTICE: The consolidated gross revenue figure cited below reflects the audited realization rate of ₹1,642.50 per ton. An earlier internal provisional memorandum had reported ₹4,820.50 Cr prior to final adjustment of the pithead bonus incentives at Mahanadi Coalfields.',
  },
  {
    id: 'blk-004',
    sectionId: 'sec-4-1',
    type: 'paragraph',
    content: 'Gross operational turnover for the quarter stands at ₹4,820.50 Cr across all active mining commands. Average net realization per metric tonne stood at ₹1,642.50, driven by higher calorific grade off-takes in Central Coalfields and Bharat Coking Coal limited divisions.',
    citationId: 'ev-001',
    evidenceRef: {
      documentName: 'CIL_FY26_Q3_Consolidated_Financial_Ledger.xlsx',
      location: 'March_Consolidated_Summary!G27:G31',
      verified: false,
    },
  },
  {
    id: 'blk-005',
    sectionId: 'sec-4-1',
    type: 'table',
    caption: 'Table 4.1.1: Subsidiary Revenue & Realization Matrix (Q3 FY26 Audited)',
    tableData: {
      headers: ['Operating Subsidiary', 'Dispatched Tonnage (MT)', 'Avg Realization / Ton', 'Gross Realization (₹ Cr)', 'FSA Share (%)'],
      rows: [
        ['Bharat Coking Coal Ltd (BCCL)', '8.45 MT', '₹2,140.00', '₹1,808.30 Cr', '78.2%'],
        ['Central Coalfields Ltd (CCL)', '6.12 MT', '₹1,580.00', '₹966.96 Cr', '84.0%'],
        ['Mahanadi Coalfields Ltd (MCL)', '15.34 MT', '₹1,393.40', '₹2,137.54 Cr', '91.5%'],
        ['Consolidated Total', '29.91 MT', '₹1,642.50', '₹4,912.80 Cr', '86.4%'],
      ],
    },
  },
  {
    id: 'blk-006',
    sectionId: 'sec-4-1',
    type: 'chart',
    caption: 'Figure 4.1: Comparative Subsidiary Revenue Contribution (₹ Crores)',
    chartConfig: {
      type: 'bar',
      title: 'Gross Revenue by Operating Command (₹ Cr)',
      data: [
        { label: 'BCCL Dhanbad', value: 1808.3 },
        { label: 'CCL Ranchi', value: 966.96 },
        { label: 'MCL Sambalpur', value: 2137.54 },
      ],
    },
  },
  {
    id: 'blk-007',
    sectionId: 'sec-4-1',
    type: 'paragraph',
    content: 'E-auction realizations continued to command a premium of 38.2% over notify Fuel Supply Agreement floor tariffs. This was supported by sustained demand from non-power captive metallurgical and sponge-iron producers in the eastern manufacturing belt.',
  },
];

export const INITIAL_ASSET_RECORDS: AssetRecord[] = [
  {
    id: 'ast-001',
    filename: 'Gevra_Opencast_Pit_Drone_Survey_Ortho.png',
    sourceDocument: 'Aerial_Drone_Surveys_Mine_Pit_A_OpenCast.png',
    page: 1,
    dateExtracted: '2026-02-15 10:05',
    description: 'Orthomosaic aerial survey map showing slope contour benches and haulage road gradients in Gevra mine pit expansion.',
    detectedRelevance: 'High',
    usedInReport: true,
    resolution: '3840 x 2160 (4K UHD)',
    dimensions: { width: 3840, height: 2160 },
    category: 'Map',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'ast-002',
    filename: 'Heavy_Electric_Dragline_Excavator_MCL.png',
    sourceDocument: 'Mahanadi_Coalfields_Safety_Inspection_Scanned_Dec25.pdf',
    page: 12,
    dateExtracted: '2026-02-14 09:40',
    description: 'Side-profile technical inspection photograph of 24-cubic-meter dragline excavator bucket wear patterns and boom stress points.',
    detectedRelevance: 'High',
    usedInReport: true,
    resolution: '1920 x 1080',
    dimensions: { width: 1920, height: 1080 },
    category: 'Technical Schema',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'ast-003',
    filename: 'Ground_Mounted_Solar_PV_Sambalpur_Array.png',
    sourceDocument: 'Board_Resolution_Renewable_CapEx_Solar_FY26.docx',
    page: 8,
    dateExtracted: '2026-02-14 09:44',
    description: 'Architectural schematic layout of proposed 400 MW solar park on backfilled mine overburden ground.',
    detectedRelevance: 'Medium',
    usedInReport: false,
    resolution: '2048 x 1536',
    dimensions: { width: 2048, height: 1536 },
    category: 'Diagram',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'ast-004',
    filename: 'Rapid_Coal_Loading_Silo_Railway_Rake.png',
    sourceDocument: 'Western_Coalfields_Production_Telemetry_Summary.pdf',
    page: 19,
    dateExtracted: '2026-02-14 09:46',
    description: 'Continuous automated silo chute loading BOXN rail rake at 4,000 tonnes per hour speed with moisture sensor readout.',
    detectedRelevance: 'Supporting',
    usedInReport: false,
    resolution: '1920 x 1280',
    dimensions: { width: 1920, height: 1280 },
    category: 'Site Photo',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
  },
];

export const INITIAL_VALIDATION_ISSUES: ValidationIssueItem[] = [
  {
    id: 'val-001',
    category: 'Numerical',
    severity: 'error',
    title: 'Discrepancy in Q3 Gross Turnover calculation',
    description: 'Paragraph text states "₹4,820.50 Cr", whereas Table 4.1.1 and verified ledger sheet March_Consolidated_Summary!G27:G31 total is "₹4,912.80 Cr" (Delta: +₹92.30 Cr).',
    targetSectionId: 'sec-4-1',
    targetSectionTitle: '4.1 Turnover, FSA Realizations & E-Auction Premiums',
    targetBlockId: 'blk-004',
    sourceDocumentRef: 'CIL_FY26_Q3_Consolidated_Financial_Ledger.xlsx',
    suggestedAction: 'Update paragraph value to ₹4,912.80 Cr and verify subsidiary contribution breakdown.',
  },
  {
    id: 'val-002',
    category: 'Source/provenance',
    severity: 'warning',
    title: 'Uncited statistical assertion in Section 2.1',
    description: 'Claim stating "Captive railway rake turn-around time contracted to 4.2 hours" lacks an active provenance citation tag.',
    targetSectionId: 'sec-2-1',
    targetSectionTitle: '2.1 Raw Coal Extraction vs Annual Target Allocations',
    sourceDocumentRef: 'Western_Coalfields_Production_Telemetry_Summary.pdf',
    suggestedAction: 'Link to Section 4 of Western Coalfields Telemetry Report (Page 18).',
  },
  {
    id: 'val-003',
    category: 'Images',
    severity: 'warning',
    title: 'Figure 4.1 is missing an explicit data source caption footnote',
    description: 'Visual chart rendered without statutory source attribution line mandated for financial regulatory filings.',
    targetSectionId: 'sec-4-1',
    targetSectionTitle: '4.1 Turnover, FSA Realizations & E-Auction Premiums',
    targetBlockId: 'blk-006',
    suggestedAction: 'Add footnote: "Source: Directorate of Commercial Accounts, CIL Kolkata".',
  },
  {
    id: 'val-004',
    category: 'Temporal',
    severity: 'pass',
    title: 'Reporting period boundary consistency verified',
    description: 'All 34 cited documents fall strictly within Oct 1, 2025 to Feb 20, 2026 data capture window.',
    targetSectionId: 'sec-1',
    targetSectionTitle: 'Executive Overview',
  },
  {
    id: 'val-005',
    category: 'Structure',
    severity: 'pass',
    title: 'All mandatory statutory compliance headings present',
    description: 'Includes DGMS Mine Safety, MoEFCC Environmental Clearance, and Comptroller Audit sections.',
    targetSectionId: 'sec-7',
    targetSectionTitle: '7. Statutory Governance, Internal Audit & Regulatory Disclosures',
  },
  {
    id: 'val-006',
    category: 'Tables',
    severity: 'pass',
    title: 'Table 4.1.1 column sum verified mathematically',
    description: 'Calculated 1,808.30 + 966.96 + 2,137.54 = ₹4,912.80 Cr matching ledger exact total.',
    targetSectionId: 'sec-4-1',
    targetSectionTitle: '4.1 Turnover, FSA Realizations & E-Auction Premiums',
    targetBlockId: 'blk-005',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'aud-901',
    timestamp: '2026-02-28 16:44:12',
    user: 'sysadmin@cil-airgap.internal (Chief Technical Evaluator)',
    category: 'Agent Action',
    severity: 'info',
    action: 'Local AI Evidence Verification Query',
    target: 'Section 4.1 Paragraph [blk-004]',
    details: 'Queried local vector-BM25 hybrid engine for turnover provenance across CIL_FY26_Q3_Consolidated_Financial_Ledger.xlsx.',
    ipOrOrigin: '127.0.0.1 (Tauri IPC Bridge)',
    verificationHash: '8e4a90f19c28e4720918bd5829a1b02938475a1c',
  },
  {
    id: 'aud-902',
    timestamp: '2026-02-28 16:30:05',
    user: 'sysadmin@cil-airgap.internal',
    category: 'Data Ingestion',
    severity: 'info',
    action: 'OCR Batch Completed',
    target: 'Mahanadi_Coalfields_Safety_Inspection_Scanned_Dec25.pdf',
    details: '42 pages processed via local CUDA PaddleOCR. 12 tables and 16 image assets extracted to local workspace cache.',
    ipOrOrigin: '127.0.0.1 (Local Daemon)',
    verificationHash: '3948572019abcef98234710928374619a0293847',
  },
  {
    id: 'aud-903',
    timestamp: '2026-02-28 15:10:48',
    user: 'auditor.dgms@cil-airgap.internal',
    category: 'Manual Edit',
    severity: 'info',
    action: 'Content Revision',
    target: 'Section 1.1 Macroeconomic Environment',
    details: 'User updated fuel supply security allocation quota to align with Ministry circular #420-B.',
    ipOrOrigin: '127.0.0.1 (Editor Canvas)',
    verificationHash: 'f401928374619028475610293847561029384756',
  },
  {
    id: 'aud-904',
    timestamp: '2026-02-28 14:02:11',
    user: 'sysadmin@cil-airgap.internal',
    category: 'Configuration Change',
    severity: 'warning',
    action: 'Airgap Security Policy Re-affirmed',
    target: 'Local AI Inference Gateway',
    details: 'External network sockets validated in blocked state. Model Llama-3.3-70B running strictly on localhost:8484.',
    ipOrOrigin: '127.0.0.1 (Tauri Security Core)',
    verificationHash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
  },
  {
    id: 'aud-905',
    timestamp: '2026-02-27 11:20:30',
    user: 'compliance.officer@cil-airgap.internal',
    category: 'Export',
    severity: 'info',
    action: 'Preliminary Draft PDF Compiled',
    target: 'Report #rep-001 (Version 0.8 Beta)',
    details: 'Rendered 48 pages via local Typst compiler. Watermarked: "CONFIDENTIAL • INTERNAL CIL USE ONLY".',
    ipOrOrigin: '127.0.0.1 (Local Print Spooler)',
    verificationHash: '99887766554433221100aabbccddeeff00112233',
  },
];
